### ISSUE TITLE
Delete/update mapshape individually

### ISSUE THREAD

**Issue by kttary** [ngageoint/geopackage-android-map#12]
I added feature table to the map with following code:

```
try{
    while(featureCursor.moveToNext()){
        FeatureRow featureRow = featureCursor.getRow();
        GeoPackageGeometryData geometryData = featureRow.getGeometry();
        Geometry geometry = geometryData.getGeometry();
        GoogleMapShape shape = converter.toShape(geometry);
        GoogleMapShape mapShape = GoogleMapShapeConverter
                .addShapeToMap(map, shape);
        // ...
    }
}finally{
    featureCursor.close();
}
```

My intention is to edit the mapshape (polygon) / delete a particular feature by its record id. When i delete a record from geopackage i want to delete its corresponding mapshape from the map. When i update its geometry, i want to refresh the old mapshape with new geom. Thank you in advance

**Comment by bosborn** [comment]
[MapCache Android](https://github.com/ngageoint/geopackage-mapcache-android/search?q=featureShapes&unscoped_q=featureShapes) uses [FeatureShapes](https://github.com/ngageoint/geopackage-android-map/blob/master/geopackage-map/src/main/java/mil/nga/geopackage/map/geom/FeatureShapes.java) to maintain the collection of shapes on the map.

A maintained GoogleMapShape reference can removed by calling the [remove() method](https://github.com/ngageoint/geopackage-android-map/blob/9138fdfb338d7c8030002d30c7c65adad4d7bfe7/geopackage-map/src/main/java/mil/nga/geopackage/map/geom/GoogleMapShape.java#L110).

Or you can manually track a mapping between FeatureRow feature ids and GoogleMapShapes, so they can be referenced when it is time to delete or update the map shape.

For editing shapes from a map, [MapCache uses](https://github.com/ngageoint/geopackage-mapcache-android/blob/68eb59aa74cb328269259f3b7b78f88e2635c1f7/mapcache/src/main/java/mil/nga/mapcache/GeoPackageMapFragment.java#L893) [addShapeToMapAsMarkers](https://github.com/ngageoint/geopackage-android-map/blob/9138fdfb338d7c8030002d30c7c65adad4d7bfe7/geopackage-map/src/main/java/mil/nga/geopackage/map/geom/GoogleMapShapeConverter.java#L1695).

**Comment by kttary** [comment]
MapChace is a very rich sourcecode to learn. Unfortunately in my computer, using washington dc vector it throw an error when i clicked map_features action. Here is the error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: mil.nga.mapcache, PID: 12072
                  mil.nga.geopackage.GeoPackageException: Failed to retrieve features tables
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getTables(GeoPackageCoreImpl.java:254)
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getTables(GeoPackageCoreImpl.java:241)
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getFeatureTables(GeoPackageCoreImpl.java:214)
                      at mil.nga.mapcache.GeoPackageMapFragment.getFeatureSelectionDialog(GeoPackageMapFragment.java:4685)
                      at mil.nga.mapcache.GeoPackageMapFragment.selectEditFeatures(GeoPackageMapFragment.java:1320)
                      at mil.nga.mapcache.GeoPackageMapFragment.handleMenuClick(GeoPackageMapFragment.java:1261)
                      at mil.nga.mapcache.MainActivity.onOptionsItemSelected(MainActivity.java:254)
                      at android.app.Activity.onMenuItemSelected(Activity.java:3543)
                      at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1237)
                      at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
                      at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
                      at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617)
                      at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147)
                      at android.view.View.performClick(View.java:6597)
                      at android.view.View.performClickInternal(View.java:6574)
                      at android.view.View.access$3100(View.java:778)
                      at android.view.View$PerformClick.run(View.java:25885)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                   Caused by: java.sql.SQLException: Problems executing Android query: SELECT * FROM `gpkg_contents` WHERE `data_type` = 'features' 
                      at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
                      at com.j256.ormlite.android.AndroidCompiledStatement.getCursor(AndroidCompiledStatement.java:197)
                      at com.j256.ormlite.android.AndroidCompiledStatement.runQuery(AndroidCompiledStatement.java:72)
                      at com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:57)
                      at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:248)
                      at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:197)
                      at com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:278)
                      at com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:366)
                      at com.j256.ormlite.stmt.Where.query(Where.java:480)
                      at com.j256.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:254)
                      at mil.nga.geopackage.core.contents.ContentsDao.getContents(ContentsDao.java:170)
                      at mil.nga.geopackage.core.contents.ContentsDao.getTables(ContentsDao.java:136)
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getTables(GeoPackageCoreImpl.java:252)
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getTables(GeoPackageCoreImpl.java:241) 
                      at mil.nga.geopackage.factory.GeoPackageCoreImpl.getFeatureTables(GeoPackageCoreImpl.java:214) 
                      at mil.nga.mapcache.GeoPackageMapFragment.getFeatureSelectionDialog(GeoPackageMapFragment.java:4685) 
                      at mil.nga.mapcache.GeoPackageMapFragment.selectEditFeatures(GeoPackageMapFragment.java:1320) 
                      at mil.nga.mapcache.GeoPackageMapFragment.handleMenuClick(GeoPackageMapFragment.java:1261) 
                      at mil.nga.mapcache.MainActivity.onOptionsItemSelected(MainActivity.java:254) 
                      at android.app.Activity.onMenuItemSelected(Activity.java:3543) 
                      at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1237) 
                      at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776) 
                      at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148) 
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923) 
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913) 
                      at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617) 
                      at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147) 
                      at android.view.View.performClick(View.java:6597) 
                      at android.view.View.performClickInternal(View.java:6574) 
                      at android.view.View.access$3100(View.java:778) 
                      at android.view.View$PerformClick.run(View.java:25885) 
                      at android.os.Handler.handleCallback(Handler.java:873) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:6669) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
                   Caused by: android.database.sqlite.SQLiteException: no such table: gpkg_contents (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM `gpkg_contents` WHERE `data_type` = 'features'
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                      at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
E/AndroidRuntime:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
                      at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347)
                      at com.j256.ormlite.android.compat.JellyBeanApiCompatibility.rawQuery(JellyBeanApiCompatibility.java:21)
                      at com.j256.ormlite.android.AndroidCompiledStatement.getCursor(AndroidCompiledStatement.java:193)

**Comment by bosborn** [comment]
That error states that there is no gpkg_contents table in the GeoPackage, which makes the GeoPackage invalid.  Looking at the washington_dc sample data, it looks like they messed that file up.  But washington_dc_vector works ok.
